const SET_POEMLIST = "SET_POEMLIST"

const LOGGED_IN = "SET_CURRENT_POEM"

const CONTROLLED_COMPONENT = "CONTROLLED_COMPONENT"

const SET_DISPLAY_TYPE = "SET_DISPLAY_TYPE"

const SET_MARKOV_INPUT = "SET_MARKOV_INPUT"

const CLEAR_MARKOV = "CLEAR_MARKOV"

const SET_MARKOV_OUTPUT = "SET_MARKOV_OUTPUT"
